### ISSUE TITLE
Exception during startup in Play 2.5 with compile-time DI

### ISSUE THREAD

**Issue by denisftw** [chrisnappin/play-recaptcha#7]
During the startup phase, the configuration module crashes with the following exception:

```
Caused by: java.lang.RuntimeException: There is no started application
    at scala.sys.package$.error(package.scala:27)
    at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
    at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
    at scala.Option.getOrElse(Option.scala:121)
    at play.api.Play$.current(Play.scala:86)
    at com.nappin.play.recaptcha.RecaptchaModule$.checkConfiguration(RecaptchaModule.scala:42)
    at com.nappin.play.recaptcha.RecaptchaVerifier.<init>(RecaptchaVerifier.scala:63)
    at AppComponents$class.recaptchaVerifier(ApplicationLoader.scala:93)
    at AppApplicationLoader$$anon$1.recaptchaVerifier$lzycompute(ApplicationLoader.scala:29)
    at AppApplicationLoader$$anon$1.recaptchaVerifier(ApplicationLoader.scala:29)
```

It seems to me that the problem is related to using `play.api.Play.current` inside the `RecaptchaModule`.  I think the recommended way to read configuration in Play 2.5 is via the `play.api.Configuration` object that can be injected.

Maybe it makes sense to add `play.api.Configuration` to `RecaptchaVerifier`'s dependencies and then pass it to `RecaptchaModule` ?

**Comment by chrisnappin** [comment]
Hi,

  I'm afraid play-recaptcha doesn't work on play 2.5, but thanks to some pull requests a new version is currently in the works.

Cheers,

 Chris

**Comment by chrisnappin** [comment]
With release 2.0, this should be resolved. Please have a go and let me know how you get on!
